development:
    server: assethost.dev
    token: droQQ2LcESKeGPzldQr7
    
production:
    server: a.scpr.org
    token: droQQ2LcESKeGPzldQr7
    
test:
    server: assethost.dev
    token: droQQ2LcESKeGPzldQr7

scprdev:
    server: a.scpr.org
    token: droQQ2LcESKeGPzldQr7
