development:
    server: a.scpr.org
    token: droQQ2LcESKeGPzldQr7

production:
    server: a.scpr.org
    token: droQQ2LcESKeGPzldQr7
    
scprdev:
    server: a.scpr.org
    token: droQQ2LcESKeGPzldQr7
    