# NOTE Right now this file doesn't actually do anything
# And won't work because Redis isn't listening
# on the correct IP for media

development: &local
    host: localhost
    port: 6379
    db: 6
    
test:
    <<: *local
    
staging:
    <<: *local
    
production:
    host: 10.226.4.238
    port: 6379
    db: 0
