valid_elements: 
  - "+*[*]"
mode: textareas
height: 400
width: 635
theme: advanced
content_css: http://www.scpr.org/assets/application.css
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: center
theme_advanced_buttons1: bold, italic, numlist, bullist, blockquote, link, unlink, image, code
relative_urls: false
plugins: 
  - media
  - paste
theme_advanced_buttons1_add : "media"
media_strict: false
paste_auto_cleanup_on_paste: true
paste_remove_spans: true
paste_strip_class_attributes: all
paste_retain_style_properties: none
