class AdminResourceGenerator < Rails::Generators::Base
  argument :resource, type: :string
  
  def create_controller_file
    create_file "app/controllers/admin/#{resource.underscore.pluralize}_controller.rb", "class Admin::#{resource.camelize.pluralize}Controller < Admin::ResourceController\nend\n"
    create_file "spec/controllers/admin/#{resource.underscore.pluralize}_controller_spec.rb", "require \"spec_helper\"\n\ndescribe Admin::#{resource.camelize.pluralize}Controller do\n  pending \"Generated by AdminResource\" \nend\n"
    create_file "features/admin/#{resource.underscore.pluralize}.feature", "Feature: #{resource.titleize.pluralize}\n"
    create_file "features/step_definitions/admin/#{resource.underscore.pluralize}_steps.rb", "# Generated by AdminResource\n"
  end
  
  def add_method_to_model
    inject_into_class "app/models/#{resource.underscore.singularize}.rb", resource.singularize.camelize.constantize, "  administrate\n"
  end
  
  def add_resource_to_routes
    insert_into_file "config/routes.rb", "      resources :#{resource.underscore.pluralize}\n", after: "## -- AdminResource -- ##\n"
  end
end
